server:
  port: 8080
  tomcat:
    max-threads: 1000
    max-connections: 2000
    accept-count: 800

spring:
  jpa:
    #这个参数是在建表的时候，将默认的存储引擎切换为 InnoDB 用的
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    database: mysql
    #配置在日志中打印出执行的 SQL 语句信息。
    show-sql: true
    hibernate:
      #第一次建表create  后面用update,要不然每次重启都会新建表
      ddl-auto: create
#    properties:
#      hibernate:
#        format_sql: true


fxea:
  #自定义线程池参数
  threadPool:
    maxThreadNum: 25
    coreThreadNum: 5
  druid:
    type: com.alibaba.druid.pool.DruidDataSource
  datasources:
    #主库(写)
    master:
      url: jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:log4jdbc:mysql://localhost:3306/test?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
      #      driver-class-name: net.sf.log4jdbc.DriverSpy
      username: root
      password: 123456
      initial-size: 5
      #最小连接数量
      min-idle: 1
      #最大连接数量
      max-active: 500
      #获取连接时最大等待时间，单位毫秒。
      max-wait: 10000
      test-on-borrow: true
    #从库(读)
    slave:
      url: jdbc:mysql://localhost:3307/test?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
      driver-class-name: com.mysql.cj.jdbc.Driver
      #      url: jdbc:mysql://localhost:3307/test?useSSL=false&characterEncoding=UTF-8&autoReconnect=true&zeroDateTimeBehavior=convertToNull&useUnicode=true
      #      driver-class-name: net.sf.log4jdbc.DriverSpy
      username: root
      password: 123456
      initial-size: 5
      #最小连接数量
      min-idle: 1
      #最大连接数量
      max-active: 500
      #获取连接时最大等待时间，单位毫秒。
      max-wait: 10000
      test-on-borrow: true